name: Deploy jar

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Maven Package Build ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use checkout v2
        uses: actions/checkout@v2
      - name: Build package
        run: |
          ./mvnw package
          ls -al ./target
#      - name: Upload math result for job 1
#        uses: actions/upload-artifact@v3
#        with:
#          name: homework
#          path: math-homework.txt
  deploy:
    runs-on: ubuntu-latest
    steps:
#      - name: Download math result for job 1
#        uses: actions/download-artifact@v3
#        with:
#          name: homework
      - name: Pickup jar
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
#          source: "./build/libs/*.jar" # gradle
          source: "./target/*.jar" # maven
          target: "/home/ec2-user/deploy"
          strip_components: 2
#
#      - name: Transfer Deploy Script use SCP
#        uses: appleboy/scp-action@master
#        with:
#          username: ${{ secrets.USERNAME }}
#          host: ${{ secrets.HOST }}
#          port: ${{ secrets.PORT }}
#          key: ${{ secrets.PRIVATE_KEY }}
#          source: "deploy.sh"
#          target: "~/repo"
#
#      - name: Execute Server Init Script
#        uses: appleboy/ssh-action@master
#        with:
#          username: ubuntu
#          host: ${{ secrets.HOST }}
#          key: ${{ secrets.PRIVATE_KEY }}
#          script_stop: true
#          script: chmod +x /home/ubuntu/deploy/deploy.sh && sh /home/ubuntu/deploy/deploy.sh