name: Deploy jar

on:
#  workflow_dispatch:
#  workflow_run:
#    workflows: [ Maven Package Build ]
#    types:
#      - completed
  push:
#  pull_request:
    branches: [ master ]

jobs:
  artifact_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build package
        run: ./mvnw package
      - name: Display structure of build files
        run: ls -ahl ./target/*.jar
      - name: Upload build result for artifact_build job
        uses: actions/upload-artifact@v3
        with:
          name: project_artifact
          path: "./target/*.jar"
  artifact_deploy:
    if: ${{ always() }}
    needs: [ artifact_build ]
    runs-on: ubuntu-latest
    steps:
      - name: Create distribute
        run: mkdir ~/dist
      - name: Download build result for artifact_build job
        uses: actions/download-artifact@v3
        with:
          name: project_artifact
          path: dist
      - name: Display structure of downloaded files
        run: |
          pwd
          ls -alh
          ls -alh dist
      - name: Transfer artifact
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          rm: true
          source: "dist/*.jar"
          target: "/home/ec2-user/deploy"
          strip_components: 1
      - name: Display structure of transfer files
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ec2-user/deploy
            ls -alh
#
#      - name: Transfer Deploy Script use SCP
#        uses: appleboy/scp-action@master
#        with:
#          username: ${{ secrets.USERNAME }}
#          host: ${{ secrets.HOST }}
#          port: ${{ secrets.PORT }}
#          key: ${{ secrets.PRIVATE_KEY }}
#          source: "deploy.sh"
#          target: "~/repo"
#
#      - name: Execute Server Init Script
#        uses: appleboy/ssh-action@master
#        with:
#          username: ubuntu
#          host: ${{ secrets.HOST }}
#          key: ${{ secrets.PRIVATE_KEY }}
#          script_stop: true
#          script: chmod +x /home/ubuntu/deploy/deploy.sh && sh /home/ubuntu/deploy/deploy.sh